version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      parcel:
        patterns:
          - "parcel"
          - "@parcel/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
    ignore:
      - dependency-name: eslint
        update-types:
          - version-update:semver-major
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
