name: Publish Web Extension

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run webext:pack
      - run: npm run webext:publish
        env:
          FIREFOX_JWT_ISSUER: ${{secrets.FIREFOX_JWT_ISSUER}}
          FIREFOX_JWT_SECRET: ${{secrets.FIREFOX_JWT_SECRET}}
